services:
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:v1.12.4-ls127@sha256:d5bf824d613212795e5505fbb4245b847f30d1a4d4d4f0bafbfd78f6e7fc8381
    restart: unless-stopped
    container_name: speedtest
    ports:
      - 127.0.0.1:8088:80
    volumes:
      - data:/config
    environment:
      PUID: 1000 
      PGID: 1000
      APP_KEY: ${SPEEDTEST_APP_KEY}
      DB_CONNECTION: sqlite
      SPEEDTEST_SCHEDULE: 6 */2 * * *
volumes:
  data:
