services:
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:v1.13.4-ls131@sha256:d3a733cb62b67866fcae7d8e982feeeee48635dc09a5ecf730c37088de55803c
    restart: unless-stopped
    container_name: speedtest
    ports:
      - 127.0.0.1:8088:80
    volumes:
      - data:/config
    environment:
      PUID: 1000 
      PGID: 1000
      APP_KEY: ${SPEEDTEST_APP_KEY}
      DB_CONNECTION: sqlite
      SPEEDTEST_SCHEDULE: 6 */2 * * *
volumes:
  data:
