services:
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:v1.13.8-ls135@sha256:661d666afc3cab668abdb3509583a841822015045e50ee94d4133faff44310ce
    restart: unless-stopped
    container_name: speedtest
    ports:
      - 127.0.0.1:8088:80
    volumes:
      - data:/config
    environment:
      PUID: 1000 
      PGID: 1000
      APP_KEY: ${SPEEDTEST_APP_KEY}
      DB_CONNECTION: sqlite
      SPEEDTEST_SCHEDULE: 6 */2 * * *
      SPEEDTEST_EXTERNAL_IP_URL: https://api.ipify.org/
volumes:
  data:
