services:
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:v1.8.0-ls120@sha256:2e655913575f15fb73a3974eceefd110bae59e30492c4c3b14b9705ca75ada5e
    restart: unless-stopped
    container_name: speedtest
    ports:
      - 8443:443
    volumes:
      - data:/config
    environment:
      PUID: 1000 
      PGID: 1000
      APP_KEY: ${SPEEDTEST_APP_KEY}
      DB_CONNECTION: sqlite
      SPEEDTEST_SCHEDULE: 6 */2 * * *
volumes:
  data:
