services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:v1.6.3-ls97@sha256:7d855bbd09f1166a8ef5b3345ae7866948bb2fc263620c1d5983e82111a058d7
    restart: unless-stopped
    container_name: speedtest-tracker
    ports:
      - 8443:443
    volumes:
      - data:/config
    environment:
      PUID: 1000 
      PGID: 1000
      APP_KEY: ${SPEEDTEST_APP_KEY}
      DB_CONNECTION: sqlite
volumes:
  data:
