services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1.6.2
    container_name: pocket-id
    restart: unless-stopped
    env_file: secrets.enc.env
    ports:
      - 127.0.0.1:1411:1411
    volumes:
      - data:/app/data
    healthcheck:
      test: "curl -f http://pocket-id:1411/healthz"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
volumes:
  data:
