services:
  glance:
    container_name: glance
    image: docker.io/glanceapp/glance:v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
    ports:
      - 127.0.0.1:8080:8080
    environment:
      DOMAIN: ${GLANCE_DOMAIN}
      SPEEDTEST_URL: ${GLANCE_SPEEDTEST_URL}
      SPEEDTEST_TRACKER_API_TOKEN: ${GLANCE_SPEEDTEST_API_TOKEN}
