services:
  atuin:
    image: ghcr.io/atuinsh/atuin:v18.6.1
    container_name: atuin-server
    restart: always
    ports:
      - 8888:8888
    volumes:
      - "./config:/config"
    links:
      - postgresql:db
    environment:
      ATUIN_DB_URI: postgres://${ATUIN_DB_USERNAME}:${ATUIN_DB_PASSWORD}@db/${ATUIN_DB_NAME}
      RUST_LOG: info,atuin_server=debug
    command: server start
  postgresql:
    image: postgres:14
    container_name: atuin-database
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - database:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
volumes:
  database:
