services:
  atuin:
    image: ghcr.io/atuinsh/atuin:v18.12.0@sha256:e953fa9e36ef571d3cb2f9746426129025b8101ad4b88cd0da6783d524cca431
    container_name: atuin-server
    restart: always
    ports:
      - 127.0.0.1:8888:8888
    volumes:
      - "./config:/config"
    links:
      - postgresql:db
    environment:
      ATUIN_DB_URI: postgres://${ATUIN_DB_USERNAME}:${ATUIN_DB_PASSWORD}@db/${ATUIN_DB_NAME}
      RUST_LOG: info,atuin_server=debug
    command: server start
  postgresql:
    image: postgres:14@sha256:962ffbe9f6418387643411b127c1db27465e5a23b9a8849bfaf45fa6323963ce
    container_name: atuin-database
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - database:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
volumes:
  database:
