services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy:2.7.1@sha256:900f5b6ab9d41e869ffb6761900c0da9f23d6d5ffd55215265671028405e485c
    container_name: babybuddy
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - TZ=America/Chicago
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000,https://babybuddy.cleek.xyz
    volumes:
      - data:/config
    restart: unless-stopped
volumes:
  data:
    driver: local
