services:
  dozzle:
    container_name: dozzle
    image: docker.io/amir20/dozzle:v8.14.12@sha256:0df89c904da71e94a0c9ed3c89a890f01488321b5f10ac1e0c0bedcead9af6e4
    volumes:
      - ./certs:/certs
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:8888:8080
    environment:
      - DOZZLE_REMOTE_AGENT=${DOZZLE_AGENT}
      - DOZZLE_CERT=/certs/cert.enc.pem
      - DOZZLE_KEY=/certs/key.enc.pem
      - DOZZLE_NO_ANALYTICS=true
