services:
  dozzle:
    container_name: dozzle
    image: docker.io/amir20/dozzle:v10.0.5@sha256:b677dd4b37ca35862593eb99fccb44236e726a8741b15e0bf81213d376bdbb73
    volumes:
      - ./certs:/certs
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:8888:8080
    environment:
      - DOZZLE_REMOTE_AGENT=${DOZZLE_AGENT}
      - DOZZLE_CERT=/certs/cert.enc.pem
      - DOZZLE_KEY=/certs/key.enc.pem
      - DOZZLE_NO_ANALYTICS=true
