services:
  dozzle:
    container_name: dozzle
    image: docker.io/amir20/dozzle:v9.0.1@sha256:a7529f02748a9520a4f372f7b349e099bb0bc6ae93c2be9d85945f51d45f8967
    volumes:
      - ./certs:/certs
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:8888:8080
    environment:
      - DOZZLE_REMOTE_AGENT=${DOZZLE_AGENT}
      - DOZZLE_CERT=/certs/cert.enc.pem
      - DOZZLE_KEY=/certs/key.enc.pem
      - DOZZLE_NO_ANALYTICS=true
