services:
  dozzle-agent:
    image: docker.io/amir20/dozzle:v8.14.10@sha256:9477f50189e583c7c118233619b08dbe724cb98dfdfe17be042b5c472807de37
    container_name: dozzle-agent
    command: agent
    volumes:
      - ${DOZZLE_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./certs:/certs
    ports:
      - 7007:7007
    env_files:
      - ${HOSTNAME}.enc.env
