services:
  dozzle-agent:
    image: docker.io/amir20/dozzle:v8.14.11@sha256:84650f9f34f576c3e8dae0bc93b438929fec0e1bd48f33b8719a6780cd78cb78
    container_name: dozzle-agent
    command: agent
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./certs:/certs
    ports:
      - 7007:7007
    environment:
      - DOZZLE_CERT=${DOZZLE_CERT}
      - DOZZLE_KEY=${DOZZLE_KEY}
      - DOZZLE_NO_ANALYTICS=${DOZZLE_NO_ANALYTICS}
      - DOZZLE_HOSTNAME=${DOZZLE_HOSTNAME}
