services:
  dozzle-agent:
    image: docker.io/amir20/dozzle:v9.0.1@sha256:a7529f02748a9520a4f372f7b349e099bb0bc6ae93c2be9d85945f51d45f8967
    container_name: dozzle-agent
    command: agent
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./certs:/certs
    ports:
      - 7007:7007
    environment:
      - DOZZLE_CERT=${DOZZLE_CERT}
      - DOZZLE_KEY=${DOZZLE_KEY}
      - DOZZLE_NO_ANALYTICS=${DOZZLE_NO_ANALYTICS}
      - DOZZLE_HOSTNAME=${DOZZLE_HOSTNAME}
