services:
  dozzle-agent:
    image: docker.io/amir20/dozzle:v9.0.3@sha256:2d59d09503f2c947133a4f231fdeb1f4c99e23aa0d4137f81bb1a6318e0e06cf
    container_name: dozzle-agent
    command: agent
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./certs:/certs
    ports:
      - 7007:7007
    environment:
      - DOZZLE_CERT=${DOZZLE_CERT}
      - DOZZLE_KEY=${DOZZLE_KEY}
      - DOZZLE_NO_ANALYTICS=${DOZZLE_NO_ANALYTICS}
      - DOZZLE_HOSTNAME=${DOZZLE_HOSTNAME}
