services:
  dozzle-agent:
    image: docker.io/amir20/dozzle:v8.14.8@sha256:0f987e852dad0eea1c3465c85a4ff1eef5ce693bdee7d030950050f073ab7d4e
    container_name: dozzle-agent
    command: agent
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
    ports:
      - 7007:7007
    environment:
      - DOZZLE_CERT=/certs/cert.enc.pem
      - DOZZLE_KEY=/certs/key.enc.pem
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_HOSTNAME=chicago
