services:
  it-tools:
    image: docker.io/corentinth/it-tools:2024.10.22-7ca5933@sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f
    container_name: it-tools
    ports:
      - '127.0.0.1:8080:80'
    restart: unless-stopped
