services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.9.1@sha256:8c5c7765ca5f7f3070f08482aca8102c2b43193777fe958e06d86b153ec18f5f
    container_name: mealie
    restart: always
    ports:
      - 127.0.0.1:9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - data:/app/data/
    environment:
      ALLOW_SIGNUP: false
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      BASE_URL: ${MEALIE_URL}
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_FROM_NAME: Mealie
      SMTP_FROM_EMAIL: ${MEALIE_EMAIL}
      SMTP_AUTH_STRATEGY: TLS
      SMTP_USER: ${MEALIE_EMAIL}
      SMTP_PASSWORD: ${MEALIE_SMTP_PASS}
      OIDC_AUTH_ENABLED: true
      OIDC_CONFIGURATION_URL: ${MEALIE_OIDC_URL}
      OIDC_CLIENT_ID: ${MEALIE_OIDC_ID}
      OIDC_CLIENT_SECRET: ${MEALIE_OIDC_SECRET}
      OIDC_ADMIN_GROUP: admin
      OIDC_SIGNUP_ENABLED: true
volumes:
  data:
