services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v2.5.5@sha256:161b1ec8af9e0478797cfd75ea857c7e55af271fa7cea103cb30ab1ba5b418d8
    container_name: immich_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    volumes:
      - ${UPLOAD_LOCATION:-/tmp}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - secrets.enc.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.5-cuda@sha256:8a55459360c7bf404e899ffc9eb0c1a5db8f308a69fd7573898769197100bf13
    container_name: immich_machine_learning
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    volumes:
      - /mnt/immich-media/immich_model-cache:/cache
    env_file:
      - secrets.enc.env
    restart: always
    healthcheck:
      disable: false
  redis:
    image: docker.io/valkey/valkey:9@sha256:4503e204c900a00ad393bec83c8c7c4c76b0529cd629e23b34b52011aefd1d27
    container_name: immich_redis
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_USER: ${DB_USERNAME:-password123}
      POSTGRES_DB: ${DB_DATABASE_NAME:-db}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION:-/tmp}:/var/lib/postgresql/data
    restart: always
