services:
  uptime-kuma:
    container_name: uptime
    image: docker.io/louislam/uptime-kuma:2.0.2@sha256:4c364ef96aaddac7ec4c85f5e5f31c3394d35f631381ccbbf93f18fd26ac7cba
    restart: unless-stopped
    volumes:
      - data:/app/data
      - /run/user/1000/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:3001:3001"
volumes:
  data:
