services:
  uptime-kuma:
    container_name: uptime
    image: docker.io/louislam/uptime-kuma:2.1.3@sha256:32c352a235fd10f98b3f64a6a4345d3c0c7f4e8be7810d2e1e867f7fe2e48ba2
    restart: unless-stopped
    volumes:
      - data:/app/data
      - /run/user/1000/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:3001:3001"
volumes:
  data:
